PXP-7499: Resolve regardless of the prefix when using /index?ids
uc-cdis/indexd pull request #305
Opened 2021-05-03 15:58 UTC by MaribelleHGomez

### New Features

### Breaking Changes

### Bug Fixes

### Improvements

- Modified get_with_nonstrict prefix route (https://github.com/uc-cdis/indexd/blob/master/indexd/index/drivers/alchemy.py#L1101) to replace hardcoded prefix delimiter.
- (https://github.com/uc-cdis/indexd/blob/master/indexd/index/drivers/alchemy.py#L500) expanded logic to query additional ids by adding to id array. If the default prefix is not _None_ the id with default prefix will be appended to id array; similarly, following logic from the get_with_nonstrict prefix route, an id stripped of the default prefix will be added to the id array.
- Added test for get without prefix (https://github.com/uc-cdis/indexd/blob/chore/update_id_get/tests/test_client.py#L86)

### Dependency updates

### Deployment changes

2021-05-03 15:59 UTC, MaribelleHGomez commented
I ran tests locally but I'd like some more feedback on unit tests

2021-05-17 19:52 UTC, BinamB commented
> I ran some tests locally but I'd like some more feedback on unit tests
> These are the two tests for that area of code:
> `data_by_ids = client.get("/index/?ids={}".format(rec_1["did"])) assert data_by_ids.status_code == 200 data_list_all = data_by_ids.json`
> 
> ```
> `# with nonstrict prefix
> stripped = rec_1["did"].split("testprefix:", 1)[1]
> data_by_ids = client.get("/index/?ids={}".format(stripped))
> assert data_by_ids.status_code == 200
> data_list_all = data_by_ids.json`
> ```
> 
> also, some feedback on this (https://github.com/uc-cdis/indexd/blob/chore/update_id_get/indexd/index/drivers/alchemy.py#L511), ty

2021-05-17 19:58 UTC, BinamB commented on tests/test_client.py
>      data_list_all = data_by_ids.json
This isn't being tested anymore since in ln 90 `data_list_all` replaces this one.

2021-05-17 19:58 UTC, BinamB commented on tests/test_client.py
>      data_list_all = data_by_ids.json
So i  guess i would suggest add the same types of checks in line 92 over here.

2021-05-17 19:58 UTC, BinamB commented on tests/test_client.py
> +
I guess I would also add different types of test cases like the one we talked about in chat where a guid and a pref+guid might exist. That is something we definitely want to handle.

2021-06-07 17:07 UTC, BinamB requested changes
I think its good. Just a small comment. Could you also remind me what Pauline wanted changed as well?

2021-06-07 18:27 UTC, BinamB approved these changes

2021-06-07 20:21 UTC, BinamB approved these changes

2021-06-07 20:22 UTC, BinamB requested changes

2021-06-07 20:22 UTC, BinamB commented on indexd/index/drivers/alchemy.py
> +                    print("NO DEFAULT_PREFIX")
can you log this instead of print

2021-06-07 20:57 UTC, BinamB approved these changes

2021-06-07 21:16 UTC, merged